Fix $sheet->with(['foo' => 'bar']) not passing data to view
Currently, when using the

    $sheet->loadView('some_view')->with(['foo' => 'bar'])

form to load a blade template and inject view data, and the
Blade view 'some_view' uses the variable $foo, an error will
be thrown:

    ErrorException: Undefined variable: foo

This syntax previously worked in previous versions of this
package, and this bug was introduced in 05ab9a9 in version
2.1.11.

This bug happens because the $data argument passed to
LaravelExcelWorksheet::with($data) eventually ends up in
LaravelExcelWorksheet::addData($data), then and if $data is a
non-empty array and there is a parser set, $data is never used.

Add a regression test that currently fails on the current latest
2.1 branch, and passes with this fix applied.